apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.service_name }}-secret-{{ .Values.environment }}"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secret-store-engine
    kind: ClusterSecretStore
  target:
    name: "{{ .Values.service_name }}-secret-{{ .Values.environment }}"
  dataFrom:
  - extract:
      key: "{{ $.Values.environment }}/{{ $.Values.service_name }}/creds"