{{ if .Values.enable_secret }}
{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1beta1/ExternalSecret" }}
apiVersion: external-secrets.io/v1beta1
{{- else if .Capabilities.APIVersions.Has "external-secrets.io/v1/ExternalSecret" }}
apiVersion: external-secrets.io/v1
{{- end }}
kind: ExternalSecret
metadata:
  name: "{{ .Values.service_name }}-secret-{{ .Values.environment }}"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: cluster-secret-store-engine
    kind: ClusterSecretStore
  target:
    name: "{{ .Values.service_name }}-secret-{{ .Values.environment }}"
  dataFrom:
  - extract:
      key: "{{ $.Values.environment }}/{{ $.Values.service_name }}/creds"
{{ end }}
