{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.service_name }}-ing-{{ .Values.environment }}"
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}   

spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:   
  - host: {{ .Values.app_url }}
    http:
      paths:
      {{- with $extraPaths }}
      {{- toYaml . | nindent 10 }}
      {{- end }}
      - path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: "{{ .Values.service_name }}-svc-{{ .Values.environment }}"
            port:
              number: {{ .Values.service_port }}
{{- end -}}